security:
  continue-on-vulnerability-error: False
  ignore-vulnerabilities:
    51457:
      expires: '2023-02-01'
      reason: Seems to relate to a transient dependency not used by the app in prod.
    51668:
      expires: '2023-02-01'
      reason: Requires upgrading to sqlalchemy 2.x
