version: "3.9"

services:
  backend:
    build:
      context: backend
    command:
      uvicorn --port 9000 --host 0.0.0.0 --reload main:app
    ports:
      - "9000:9000"
    env_file: .env
    volumes:
      - ./backend:/app:delegated
      - root-home:/root:delegated

volumes:
  app-db-data:
  root-home:
