apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - env:
            - name: HELLO_FULL_STACK_APP_MODE
              value: api
            - name: HELLO_FULL_STACK_MESSAGE
              value: Hello Full Stack!
            - name: HELLO_FULL_STACK_REGION
              value: us-east-1
            - name: HELLO_FULL_STACK_STAGE
              value: prod
            - name: HELLO_FULL_STACK_VENDOR
              value: aws

            - name: NEW_RELIC_APP_NAME
              value: "hello-full-stack"
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: new-relic-license-key
                  optional: false
          name: hello-full-stack-api
metadata:
  name: hello-full-stack-api
  namespace: hello-full-stack
