apiVersion: v1
stringData:
    key: ENC[AES256_GCM,data:+2kHGGP7u1qD9TWNz0oFtVfNLBYdc6xjZpI5rWE9DyyOWdYu6o+3bg==,iv:4/wM16qWRpPQhxOUuGGxDNV1CkXDYt/QQyrBCS2+xhs=,tag:dDOdzwvrDAsAgAVMRGNiAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: new-relic-license-key
    namespace: hello-full-stack
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:498127099666:key/f117bf24-7758-4598-be24-51c2b8c03020
          created_at: "2023-04-06T14:42:47Z"
          enc: AQICAHhtok//3xzTakiz2YGH6WGuX9fOcaZ57+RwMBffCYdIigG1cedauRmeiRkAEBtVrqCeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMegsp3nr2+Oj5QHoRAgEQgDv18dRohSYaHeGyZB46N5x5/YXkOk0E3IPjDWcJRev8lg33vTYxEuEpEerCiqQk+c4yybBqxgCs9SJOXw==
          aws_profile: argocd
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-06T14:42:48Z"
    mac: ENC[AES256_GCM,data:x6QpzyeIBk4aQzYVLtYuLyJsBCXc8fwMxE/zjDrnV+G1a395JMkd4cK6VqlWq8twtfzLhNik/28tvXMjXxxKuh8wMTIQ7oPjxD9LLxvHzxgGvm95xHDzQrGcP3fJB9GJR6BFxE8ZIcd0a26OqQt0bk1gn3LMEjBEhi5+AF3jON8=,iv:qFYU4b45jD/SoMsIxv1xdoYSAA7orVa5GXoZPf8f9ao=,tag:jxJ2SYTAe9fPeFVY0zCOMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
