apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifest.yaml
images:
- name: 498127099666.dkr.ecr.us-east-1.amazonaws.com/hello-full-stack
  newTag: 2b3581cf514cfb6acada1d7589fedf0812b6cc40
