apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifest.yaml
images:
- name: 498127099666.dkr.ecr.us-east-1.amazonaws.com/hello-full-stack
  newTag: 72765a63dd05a010b799ba51c71ef2d22d9203ac
